"""
stock_report_worker.py

Plain Python module (no web framework) for fetching stock data, computing
technical-analysis features, training a lightweight classifier to predict
next-day direction, and generating/emailing a PDF report.

Designed to be called as a worker function from a Redis-streams task queue.
The top-level entry point is `generate_stock_report(ticker, email)`, which is
a pure function: it does not open any database connections. The caller
(a separate worker module) is responsible for persisting results.
"""

import os
import io
from datetime import date, timedelta, datetime

import yfinance as yf
import pandas as pd
import numpy as np
from scipy.stats import linregress

import matplotlib
matplotlib.use("Agg")  # non-interactive backend, safe for worker processes
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
)
import tempfile
from typing import Any

# Optional Plotly imports kept only for the legacy interactive chart function
# (data_plotting). Not used by the main pipeline.
import plotly.graph_objects as go
import plotly.io as pio

import requests
import base64


DISCLAIMER_TEXT = (
    "Disclaimer: This report is a demonstration of an automated reporting "
    "pipeline and does not constitute financial advice. The predicted "
    "direction is generated by a simple statistical model for illustrative "
    "purposes only and should not be used as the basis for any investment "
    "decision."
)


# ---------------------------------------------------------------------------
# Feature engineering (preserved from the original implementation)
# ---------------------------------------------------------------------------

def calculate_rs_rsi(series, period=14):
    """
    Compute Relative Strength (RS) and Relative Strength Index (RSI) using
    Wilder's smoothing method.

    Inputs:
        series (pd.Series): price series (typically Close).
        period (int): lookback period for RSI calculation (default 14).

    Returns:
        tuple(pd.Series, pd.Series): (RS, RSI) aligned to the input index.
    """
    delta = series.diff()

    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.ewm(alpha=1 / period, min_periods=period, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1 / period, min_periods=period, adjust=False).mean()

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))

    return rs, rsi


def calc_slope(series, window=5):
    """
    Compute a rolling linear-regression slope of a series.

    Inputs:
        series (pd.Series): numeric series to compute the trend slope on.
        window (int): rolling window size (default 5).

    Returns:
        pd.Series: rolling slope values aligned to the input index.
    """
    return series.rolling(window).apply(
        lambda x: linregress(range(len(x)), x)[0]
    )


def feature_generation(df):
    """
    Generate the full set of technical-analysis features used by the model
    and reports, exactly preserving the original feature engineering logic.

    Inputs:
        df (pd.DataFrame): raw OHLCV dataframe as returned by yf.download,
            indexed by date, with columns including Open, High, Low, Close,
            Volume.

    Returns:
        pd.DataFrame: the input dataframe with added columns for moving
            averages, MACD/signal/histogram, RSI, Bollinger Bands, volume
            change, ROC, OBV, stochastic %K/%D, rolling 3/5/10-day returns,
            trend slope, lagged close/volume, and the binary Target column
            (1 if Close > Open, else 0). Rows with any NaN (from rolling
            windows) are dropped.
    """
    df.columns = [
        col[0] if isinstance(col, tuple) and col[1] != ''
        else col if isinstance(col, str)
        else ''.join(col)
        for col in df.columns
    ]

    # MA Creation
    df['50DSMA'] = df['Close'].rolling(window=50).mean()
    df['200DSMA'] = df['Close'].rolling(window=200).mean()
    df['8DEMA'] = df['Close'].ewm(span=8, adjust=False).mean()

    # MACD Creation
    df['26DEMA'] = df['Close'].ewm(span=26, adjust=False).mean()
    df['12DEMA'] = df['Close'].ewm(span=12, adjust=False).mean()
    df['MACD'] = df['12DEMA'] - df['26DEMA']
    df['Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['MACD_Hist'] = df['MACD'] - df['Signal']

    # RSI Creation
    rs, rsi = calculate_rs_rsi(df['Close'], period=14)
    df['RS'] = rs
    df['RSI_14'] = rsi

    # Bollinger Band Creation
    df['BB_middle'] = df['Close'].rolling(window=20).mean()
    df['BB_std'] = df['Close'].rolling(window=20).std()
    df['BB_upper'] = df['BB_middle'] + 2 * df['BB_std']
    df['BB_lower'] = df['BB_middle'] - 2 * df['BB_std']

    # Volume Difference
    df['Volume_Change'] = df['Volume'].diff()

    # Rate of Change Creation
    df['ROC'] = df['Close'].pct_change(periods=10)

    # On Balance Volume Creation
    df['Direction'] = np.where(df['Close'] > df['Close'].shift(1), 1, -1)
    df['Direction'] = np.where(df['Close'] == df['Close'].shift(1), 0, df['Direction'])
    df['OBV'] = (df['Volume'] * df['Direction']).cumsum()

    # Stochastic Oscillator Creation
    low_min = df['Low'].rolling(window=14).min()
    high_max = df['High'].rolling(window=14).max()
    df['%K'] = 100 * ((df['Close'] - low_min) / (high_max - low_min))
    df['%D'] = df['%K'].rolling(window=3).mean()

    # Rolling Returns
    df['Return_3D'] = df['Close'].pct_change(periods=3)
    df['Return_5D'] = df['Close'].pct_change(periods=5)
    df['Return_10D'] = df['Close'].pct_change(periods=10)

    # Trend Slope
    df['Trend_Slope'] = calc_slope(df['Close'])

    # Lagged Features
    df['Lagged_Close'] = df['Close'].shift(1)
    df['Lagged_Volume'] = df['Volume'].shift(1)

    # Target Creation
    df['Target'] = (df['Close'] > df['Open']).astype(int)

    df = df.dropna()

    return df


# ---------------------------------------------------------------------------
# Data fetching
# ---------------------------------------------------------------------------

def fetch_stock_data(ticker, start="2015-01-01", end=None):
    """
    Download historical OHLCV data for a ticker via yfinance and validate it.

    Inputs:
        ticker (str): ticker symbol to fetch (e.g. "AAPL").
        start (str): start date in YYYY-MM-DD format (default "2015-01-01").
        end (str or None): end date in YYYY-MM-DD format. Defaults to
            yesterday if not provided.

    Returns:
        pd.DataFrame: raw OHLCV dataframe.

    Raises:
        ValueError: if the ticker is invalid or yfinance returns no data.
    """
    if end is None:
        end = (date.today() - timedelta(days=1)).isoformat()

    data = yf.download(ticker, start=start, end=end)

    if data is None or data.empty:
        raise ValueError(
            f"No data returned for ticker '{ticker}'. The ticker may be "
            f"invalid, delisted, or have no trading history in the "
            f"requested date range."
        )

    return data


# ---------------------------------------------------------------------------
# Model training / prediction
# ---------------------------------------------------------------------------

# Feature columns used to train and predict with the classifier.
_MODEL_FEATURES = [
    '50DSMA', '200DSMA', '8DEMA', 'MACD', 'Signal', 'MACD_Hist',
    'RSI_14', 'BB_upper', 'BB_middle', 'BB_lower', 'Volume_Change',
    'ROC', 'OBV', '%K', '%D', 'Return_3D', 'Return_5D', 'Return_10D',
    'Trend_Slope', 'Lagged_Close', 'Lagged_Volume',
]


def train_and_predict(df):
    """
    Train a simple Logistic Regression classifier on engineered features to
    predict next-day direction (Target: Close > Open), and predict the
    direction for the most recent row.

    The most recent row is excluded from training since it has no realized
    Target value yet (it represents "today"). Training uses a lightweight
    classical model so the whole operation completes in well under 5 seconds
    even for several thousand rows of daily data.

    Inputs:
        df (pd.DataFrame): feature-engineered dataframe as produced by
            feature_generation, including the Target column and all columns
            listed in _MODEL_FEATURES.

    Returns:
        dict: {
            "predicted_direction": "up" or "down",
            "confidence": float, the model's predict_proba for the
                predicted class,
            "feature_values": dict of feature name -> value used for the
                prediction (the most recent row's features),
        }

    Raises:
        ValueError: if there are not enough rows to train a model.
    """
    if len(df) < 2:
        raise ValueError(
            "Not enough data rows to train a model and make a prediction."
        )

    train_df = df.iloc[:-1]
    latest_row = df.iloc[[-1]]

    X_train = train_df[_MODEL_FEATURES]
    y_train = train_df['Target']

    if y_train.nunique() < 2:
        raise ValueError(
            "Training data contains only one class of Target values; "
            "cannot train a classifier."
        )

    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)

    X_latest = latest_row[_MODEL_FEATURES]
    predicted_class = model.predict(X_latest)[0]
    probabilities = model.predict_proba(X_latest)[0]
    class_index = list(model.classes_).index(predicted_class)
    confidence = float(probabilities[class_index])

    predicted_direction = "up" if predicted_class == 1 else "down"

    feature_values = X_latest.iloc[0].to_dict()

    return {
        "predicted_direction": predicted_direction,
        "confidence": confidence,
        "feature_values": feature_values,
    }


# ---------------------------------------------------------------------------
# PDF report generation
# ---------------------------------------------------------------------------

def _make_price_ma_chart(df):
    """
    Create a static matplotlib chart of closing price with moving averages
    overlaid, returned as an in-memory PNG buffer.

    Inputs:
        df (pd.DataFrame): feature-engineered dataframe with Close, 50DSMA,
            200DSMA, and 8DEMA columns.

    Returns:
        io.BytesIO: PNG image buffer, seeked to position 0.
    """
    recent = df.tail(252)  # roughly the last trading year
    fig, ax = plt.subplots(figsize=(7, 3.2))
    ax.plot(recent.index, recent['Close'], label='Close', color='black', linewidth=1.2)
    ax.plot(recent.index, recent['50DSMA'], label='50 DSMA', color='orange', linewidth=1)
    ax.plot(recent.index, recent['200DSMA'], label='200 DSMA', color='green', linewidth=1)
    ax.plot(recent.index, recent['8DEMA'], label='8 DEMA', color='red', linewidth=1)
    ax.set_title("Closing Price with Moving Averages")
    ax.legend(fontsize=7, loc='upper left')
    ax.tick_params(axis='x', labelrotation=45, labelsize=7)
    ax.tick_params(axis='y', labelsize=7)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=150)
    plt.close(fig)
    buf.seek(0)
    return buf


def _make_rsi_chart(df):
    """
    Create a static matplotlib chart of RSI-14 with overbought (70) and
    oversold (30) reference lines, returned as an in-memory PNG buffer.

    Inputs:
        df (pd.DataFrame): feature-engineered dataframe with an RSI_14 column.

    Returns:
        io.BytesIO: PNG image buffer, seeked to position 0.
    """
    recent = df.tail(252)
    fig, ax = plt.subplots(figsize=(7, 2.8))
    ax.plot(recent.index, recent['RSI_14'], label='RSI (14)', color='purple', linewidth=1.2)
    ax.axhline(70, color='red', linestyle='--', linewidth=1)
    ax.axhline(30, color='green', linestyle='--', linewidth=1)
    ax.set_ylim(0, 100)
    ax.set_title("RSI (14)")
    ax.tick_params(axis='x', labelrotation=45, labelsize=7)
    ax.tick_params(axis='y', labelsize=7)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=150)
    plt.close(fig)
    buf.seek(0)
    return buf


def _make_macd_hist_chart(df):
    """
    Create a static matplotlib bar chart of the MACD histogram, returned as
    an in-memory PNG buffer.

    Inputs:
        df (pd.DataFrame): feature-engineered dataframe with a MACD_Hist
            column.

    Returns:
        io.BytesIO: PNG image buffer, seeked to position 0.
    """
    recent = df.tail(252)
    colors_list = ['green' if v >= 0 else 'red' for v in recent['MACD_Hist']]
    fig, ax = plt.subplots(figsize=(7, 2.8))
    ax.bar(recent.index, recent['MACD_Hist'], color=colors_list, width=1.0)
    ax.set_title("MACD Histogram")
    ax.tick_params(axis='x', labelrotation=45, labelsize=7)
    ax.tick_params(axis='y', labelsize=7)
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format='png', dpi=150)
    plt.close(fig)
    buf.seek(0)
    return buf


def generate_pdf_report(ticker, df, prediction_result, output_path):
    """
    Generate a PDF report summarizing technical indicators and the model's
    predicted direction for a ticker, using reportlab.

    Inputs:
        ticker (str): ticker symbol the report is about.
        df (pd.DataFrame): feature-engineered dataframe (output of
            feature_generation).
        prediction_result (dict): output of train_and_predict, containing
            predicted_direction, confidence, and feature_values.
        output_path (str): filesystem path to write the PDF to.

    Returns:
        str: the output_path the PDF was saved to.
    """
    styles = getSampleStyleSheet()
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=8,
        textColor=colors.grey, spaceBefore=12,
    )

    doc = SimpleDocTemplate(output_path, pagesize=letter,
                             topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    story = []

    story.append(Paragraph(f"Stock Technical Report: {ticker}", styles["Title"]))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        styles["Normal"],
    ))
    story.append(Spacer(1, 0.2 * inch))

    direction = prediction_result["predicted_direction"]
    confidence_pct = prediction_result["confidence"] * 100
    story.append(Paragraph(
        f"<b>Predicted next-day direction:</b> {direction.upper()} "
        f"(confidence: {confidence_pct:.1f}%)",
        styles["Heading2"],
    ))
    story.append(Spacer(1, 0.15 * inch))

    latest = df.iloc[-1]
    summary_rows = [
        ["Indicator", "Latest Value"],
        ["Close", f"{latest['Close']:.2f}"],
        ["50DSMA", f"{latest['50DSMA']:.2f}"],
        ["200DSMA", f"{latest['200DSMA']:.2f}"],
        ["8DEMA", f"{latest['8DEMA']:.2f}"],
        ["RSI (14)", f"{latest['RSI_14']:.2f}"],
        ["MACD", f"{latest['MACD']:.4f}"],
        ["MACD Signal", f"{latest['Signal']:.4f}"],
        ["MACD Histogram", f"{latest['MACD_Hist']:.4f}"],
        ["Bollinger Upper", f"{latest['BB_upper']:.2f}"],
        ["Bollinger Middle", f"{latest['BB_middle']:.2f}"],
        ["Bollinger Lower", f"{latest['BB_lower']:.2f}"],
        ["Stochastic %K", f"{latest['%K']:.2f}"],
        ["Stochastic %D", f"{latest['%D']:.2f}"],
        ["OBV", f"{latest['OBV']:.0f}"],
    ]
    table = Table(summary_rows, colWidths=[2.5 * inch, 2.5 * inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
    ]))
    story.append(table)
    story.append(Spacer(1, 0.25 * inch))

    story.append(Paragraph("Closing Price &amp; Moving Averages", styles["Heading3"]))
    price_chart = _make_price_ma_chart(df)
    story.append(RLImage(price_chart, width=6.5 * inch, height=2.97 * inch))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("RSI (14)", styles["Heading3"]))
    rsi_chart = _make_rsi_chart(df)
    story.append(RLImage(rsi_chart, width=6.5 * inch, height=2.6 * inch))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("MACD Histogram", styles["Heading3"]))
    macd_chart = _make_macd_hist_chart(df)
    story.append(RLImage(macd_chart, width=6.5 * inch, height=2.6 * inch))
    story.append(Spacer(1, 0.2 * inch))

    story.append(Paragraph(DISCLAIMER_TEXT, disclaimer_style))

    doc.build(story)

    return output_path


# ---------------------------------------------------------------------------
# Email delivery
# ---------------------------------------------------------------------------

def send_report_email(to_email, ticker, pdf_path):
    """
    Send the generated PDF report as an email attachment via Resend's API.

    Reads RESEND_API_KEY from environment variables.

    Inputs:
        to_email (str): recipient email address.
        ticker (str): ticker symbol, used in subject/body.
        pdf_path (str): filesystem path to the PDF report to attach.

    Returns:
        bool: True if the email was sent successfully.

    Raises:
        RuntimeError: if RESEND_API_KEY is missing.
        requests.HTTPError: if the Resend API call fails.
    """
    api_key = os.environ.get("RESEND_API_KEY")
    if not api_key:
        raise RuntimeError("Missing required RESEND_API_KEY environment variable.")

    with open(pdf_path, "rb") as f:
        pdf_bytes = f.read()

    body = (
        f"Attached is the automated technical analysis report for {ticker}, "
        f"generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.\n\n"
        f"{DISCLAIMER_TEXT}\n"
    )

    response = requests.post(
        "https://api.resend.com/emails",
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "from": "onboarding@resend.dev",
            "to": [to_email],
            "subject": f"Automated Stock Report: {ticker}",
            "text": body,
            "attachments": [{
                "filename": os.path.basename(pdf_path),
                "content": base64.b64encode(pdf_bytes).decode(),
            }],
        },
        timeout=30,
    )
    response.raise_for_status()
    return True
# ---------------------------------------------------------------------------
# Orchestration (worker entry point)
# ---------------------------------------------------------------------------

def generate_stock_report(ticker: str, email: str) -> dict:
    """
    Top-level orchestrating function for the worker pipeline: fetch ->
    feature_generation -> train_and_predict -> generate_pdf_report ->
    send_report_email.

    This is a pure function: it performs no database I/O. The caller (a
    separate worker module reading from the Redis-streams task queue) is
    responsible for persisting the returned result.

    Any failure anywhere in the pipeline (invalid ticker, network error,
    SMTP failure, etc.) is caught and reported via the returned dict's
    "status" and "error" fields rather than raised, so it will not crash
    the calling worker process.

    Inputs:
        ticker (str): ticker symbol to generate the report for.
        email (str): recipient email address for the generated report.

    Returns:
        dict: {
            "status": "completed" or "failed",
            "ticker": ticker,
            "predicted_direction": "up"/"down" or None,
            "confidence": float or None,
            "pdf_path": str or None,
            "error": None or str,
        }
    """
    result = {
        "status": "failed",
        "ticker": ticker,
        "predicted_direction": None,
        "confidence": None,
        "pdf_path": None,
        "error": None,
    }

    try:
        ticker = ticker.upper()

        raw_data = fetch_stock_data(ticker)
        df = feature_generation(raw_data)
        prediction_result = train_and_predict(df)

        final_path = os.path.join("/tmp", f"{ticker}_report_{date.today().isoformat()}.pdf")
        fd, tmp_path = tempfile.mkstemp(suffix=".pdf", dir="/tmp")
        os.close(fd)
        generate_pdf_report(ticker, df, prediction_result, tmp_path)
        os.replace(tmp_path, final_path)
        pdf_path = final_path

        send_report_email(email, ticker, pdf_path)

        result["status"] = "completed"
        result["predicted_direction"] = prediction_result["predicted_direction"]
        result["confidence"] = prediction_result["confidence"]
        result["pdf_path"] = pdf_path

    except Exception as exc:
        result["status"] = "failed"
        result["error"] = str(exc)

    return result


# ---------------------------------------------------------------------------
# Optional legacy interactive chart function (not used by the pipeline above)
# ---------------------------------------------------------------------------

def data_plotting(df):
    """
    Build a set of interactive Plotly charts (closing price, volume overlay,
    moving averages, candlestick, MACD/signal, MACD histogram, RSI,
    Bollinger Bands) for an interactive frontend chart view.

    This function is preserved for optional future use (e.g. an interactive
    frontend) but is NOT called by generate_stock_report.

    Inputs:
        df (pd.DataFrame): feature-engineered dataframe as produced by
            feature_generation.

    Returns:
        dict: mapping of chart name -> Plotly figure JSON string
            (via plotly.io.to_json), keyed by: closing_price, volume_overlay,
            moving_averages, candlestick, macd_signal, macd_histogram, rsi,
            bollinger_bands.
    """
    graphs = {}

    end_date_data = df.index.max()
    start_date_segment = max(df.index.min(), end_date_data - timedelta(days=365))

    common_layout: dict[str, Any] = dict(
        plot_bgcolor='white',
        paper_bgcolor='white',
        font=dict(family="Segoe UI, sans-serif", size=13, color="#222"),
        margin=dict(t=100, l=50, r=30, b=50),
        hovermode="x unified",
        height=500,
        xaxis=dict(
            showgrid=True,
            gridcolor='lightgrey',
            linecolor='darkgrey',
            linewidth=1,
            rangeslider=dict(visible=True, thickness=0.05),
            rangeselector=dict(
                buttons=list([
                    dict(count=1, label="1m", step="month", stepmode="backward"),
                    dict(count=6, label="6m", step="month", stepmode="backward"),
                    dict(count=1, label="YTD", step="year", stepmode="todate"),
                    dict(count=1, label="1y", step="year", stepmode="backward"),
                    dict(step="all")
                ]),
                y=1.02,
                yanchor="bottom"
            ),
            range=[start_date_segment, end_date_data],
            fixedrange=False
        ),
        yaxis=dict(
            showgrid=True,
            gridcolor='lightgrey',
            linecolor='darkgrey',
            linewidth=1,
            zeroline=False,
            fixedrange=False
        )
    )

    # 1. Closing Price
    fig1 = go.Figure()
    fig1.add_trace(go.Scatter(x=df.index, y=df['Close'], mode='lines', name='Close',
                              line=dict(color='#1f77b4', width=2)))
    fig1.update_layout(title="Closing Price", yaxis_title="Price (INR)", **common_layout)
    graphs['closing_price'] = pio.to_json(fig1)

    # 2. Volume Overlay
    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(x=df.index, y=df['Close'], name='Close',
                              line=dict(color='#1f77b4', width=2), yaxis="y1"))
    fig2.add_trace(go.Bar(x=df.index, y=df['Volume'], name='Volume',
                          marker=dict(color='rgba(128,128,128,0.4)'), yaxis="y2"))

    volume_layout = common_layout.copy()
    volume_layout.pop('yaxis', None)

    fig2.update_layout(
        title="Volume Overlay",
        yaxis=dict(title="Price (INR)", side='left', fixedrange=False,
                  showgrid=True, gridcolor='lightgrey', linecolor='darkgrey', linewidth=1, zeroline=False),
        yaxis2=dict(title="Volume", overlaying="y", side="right", showgrid=False, fixedrange=False),
        barmode='overlay',
        **volume_layout
    )
    graphs['volume_overlay'] = pio.to_json(fig2)

    # 3. Moving Averages
    fig3 = go.Figure()
    fig3.add_trace(go.Scatter(x=df.index, y=df['Close'], name='Close', line=dict(color='black')))
    fig3.add_trace(go.Scatter(x=df.index, y=df['50DSMA'], name='50 DSMA', line=dict(color='orange')))
    fig3.add_trace(go.Scatter(x=df.index, y=df['200DSMA'], name='200 DSMA', line=dict(color='green')))
    fig3.add_trace(go.Scatter(x=df.index, y=df['8DEMA'], name='8 DEMA', line=dict(color='red')))
    fig3.update_layout(title="Moving Averages", yaxis_title="Price (INR)", **common_layout)
    graphs['moving_averages'] = pio.to_json(fig3)

    # 4. Candlestick
    fig4 = go.Figure(data=[go.Candlestick(
        x=df.index,
        open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'],
        increasing=dict(line=dict(color="green", width=1.5)),
        decreasing=dict(line=dict(color="red", width=1.5))
    )])
    fig4.update_layout(title="Candlestick Chart", yaxis_title="Price (INR)", **common_layout)
    graphs['candlestick'] = pio.to_json(fig4)

    # 5. MACD & Signal
    fig5 = go.Figure()
    fig5.add_trace(go.Scatter(x=df.index, y=df['MACD'], name='MACD', line=dict(color='red')))
    fig5.add_trace(go.Scatter(x=df.index, y=df['Signal'], name='Signal', line=dict(color='blue')))
    fig5.update_layout(title="MACD & Signal Line", yaxis_title="Value", **common_layout)
    graphs['macd_signal'] = pio.to_json(fig5)

    # 6. MACD Histogram
    pos = df['MACD_Hist'].copy()
    pos[pos < 0] = np.nan
    neg = df['MACD_Hist'].copy()
    neg[neg >= 0] = np.nan

    fig6 = go.Figure()
    fig6.add_trace(go.Bar(x=df.index, y=pos, name="Positive", marker=dict(color='rgba(44,160,44,0.7)')))
    fig6.add_trace(go.Bar(x=df.index, y=neg, name="Negative", marker=dict(color='rgba(214,39,40,0.7)')))
    fig6.update_layout(title="MACD Histogram", yaxis_title="MACD Value", barmode="overlay", **common_layout)
    graphs['macd_histogram'] = pio.to_json(fig6)

    # 7. RSI
    fig7 = go.Figure()
    fig7.add_trace(go.Scatter(x=df.index, y=df['RSI_14'], name='RSI (14)', line=dict(color='purple')))
    fig7.add_shape(type="line", x0=start_date_segment, x1=end_date_data, y0=70, y1=70,
                   line=dict(color='red', dash='dash'))
    fig7.add_shape(type="line", x0=start_date_segment, x1=end_date_data, y0=30, y1=30,
                   line=dict(color='green', dash='dash'))

    rsi_layout = common_layout.copy()
    rsi_layout.pop('yaxis', None)

    fig7.update_layout(
        title="RSI (14)",
        yaxis=dict(title="RSI", range=[0, 100], fixedrange=False,
                  showgrid=True, gridcolor='lightgrey', linecolor='darkgrey', linewidth=1, zeroline=False),
        **rsi_layout
    )
    graphs['rsi'] = pio.to_json(fig7)

    # 8. Bollinger Bands
    fig8 = go.Figure()
    fig8.add_trace(go.Scatter(x=df.index, y=df['Close'], name='Close', line=dict(color='black')))
    fig8.add_trace(go.Scatter(x=df.index, y=df['BB_upper'], name='Upper Band', line=dict(color='brown', dash='dash')))
    fig8.add_trace(go.Scatter(x=df.index, y=df['BB_middle'], name='Middle Band', line=dict(color='gray')))
    fig8.add_trace(go.Scatter(x=df.index, y=df['BB_lower'], name='Lower Band', line=dict(color='brown', dash='dash')))
    fig8.update_layout(title="Bollinger Bands", yaxis_title="Price (INR)", **common_layout)
    graphs['bollinger_bands'] = pio.to_json(fig8)

    return graphs